spring.application.name= account-service
server.port= 8092
account.name= account-from-central-config-repo
eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka/
eureka.instance.hostname=account-service
eureka.instance.prefer-ip-address=true
