server.port= 8080
spring.application.name= api-gateway
spring.cloud.gateway.server.webflux.discovery.locator.enabled= true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id= true
eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka/
product.service.uri=http://product-service:8091
account.service.uri=http://account-service:8092
order.service.uri=http://order-service:8093

