spring.application.name= product-service
server.port= 8091
product.name= product-from-central-config-repo
eureka.client.service-url.defaultZone= http://discovery-server:8761/eureka/
eureka.instance.hostname=product-service
eureka.instance.prefer-ip-address=true

